# Generated by Django 5.2.1 on 2025-06-03 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diario", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tratamento",
            name="sintomas",
        ),
        migrations.AddField(
            model_name="sintoma",
            name="horario",
            field=models.TimeField(default="09:00"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="sintoma",
            name="data",
            field=models.DateField(),
        ),
    ]
