# Generated by Django 5.2.1 on 2025-06-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diario", "0002_remove_tratamento_sintomas_sintoma_horario_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tratamento",
            name="data_fim",
            field=models.DateField(default="2025-06-05"),
            preserve_default=False,
        ),
    ]
